### ISSUE TITLE
Remove "polymer lint" from Travis build because it fails with mixins

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/emoji-reaction-selector#3]
The Travis build fails with:
```
emoji-reaction-selector.html(47,38) warning [databind-with-unknown-property] - getAllEmojis is not declared or used more than once. Did you mean: selected

		[[getEmoji(value)]]
		  ~~~~~~~~
emoji-reaction.html(21,4) warning [databind-with-unknown-property] - getEmoji is not declared or used more than once. Did you mean: title

		[[getEmoji(value)]]
		  ~~~~~~~~
emoji-reaction.html(21,4) warning [databinding-calls-must-be-functions] - getEmoji is not a known method on emoji-reaction
Found 3 warnings.
The command "$(npm bin)/polymer lint" failed and exited with 1 during .
```

`getEmoji()` is a valid method defined in a mixin (https://github.com/Collaborne/emoji-reaction-selector/blob/master/emoji-reaction-mixin.html#L12).

Not detecting methods from mixins is a known issue in "polymer lint": https://github.com/Polymer/polymer-cli/issues/796

**Comment by ankon** [comment]
Actually there is a secondary problem here, which is that polymer-lint is absolutely anal with warnings: https://github.com/Polymer/polymer-project-config/pull/20#issuecomment-323988240

I'll go with the approach I outlined there rather than removing the lint invocation completely.
